### ISSUE TITLE
The 0 value does not generate output.

### ISSUE THREAD

**Issue by rki** [twigkit/tempo#12]
Example:

If the index = 0 then <select onchange="update_hours_list({{index}})"> gives to <select onchange="update_hours_list()>.

**Comment by mrolafsson** [comment]
Thanks for reporting this. This was an issue where an eval of the given item from the object in resulting to 0 meant that a legitimate zero value was interpreted as false. This is now fixed in master. Please verify that this resolves your problem. Thanks. Stefan

**Comment by mrolafsson** [comment]
In hindsight this should probably just strictly check for undefined (because presumably we will have the same issue with false values.

**Comment by mrolafsson** [comment]
Now strictly checking for undefined so false and 0 values work in master branch.

**Comment by rki** [comment]
Thanks for quick fixing. It works now.
