### ISSUE TITLE
Support special atbute {{tempo.index}} 

### ISSUE THREAD

**Issue by rki** [twigkit/tempo#13]
It would be nice to use some kind of special atribute {{tempo.index}} which would give the index of the element in the rendered collection.

**Comment by 13k** [comment]
I also support this feature request. Just a use case example: I was trying to render a list of question/answers for a FAQ, but I also needed to create anchor links for better navigation so I could use the index to automatically create those anchors.

**Comment by twigkit** [comment]
Yes I agree, sorry this fell between the cracks for 1.3, I'll make sure this is in the next update which I'm close to finishing.

**Comment by twigkit** [comment]
Added in v1.4

**Comment by baltauger** [comment]
A quick note/observation: when using append() or prepend() instead of doing a full render, _tempo.index resets to 0, and not at the last used index. FWIW
