### ISSUE TITLE
Attributes of tags nested into data-template are not being rendered

### ISSUE THREAD

**Issue by anibal** [twigkit/tempo#14]
This is my html code:

```
<ul id="stuffs">
  <li data-template>
    [<a href="documents/{{code}}">{{code}}</a>]
    {{name}}
  </li>
</ul>
```

Then I trigger the render:

```
Tempo.prepare("stuffs").render(this.stuffs);
```

And this is the result:

```
<ul id="stuffs">  
  <li data-template="">
    [<a href="documents/%7B%7Bcode%7D%7D">1234</a>] foo bar
  </li><li data-template="">
    [<a href="documents/%7B%7Bcode%7D%7D">4321</a>] 4321 bar foo
  </li>
</ul>
```

(Copied from Firebug) Note the suspicious "%7B%7B"

**Comment by twigkit** [comment]
Thanks Anibal! Can you also put in a JSON example? If you can email me an example page that executes that would be even better :)

**Comment by anibal** [comment]
[{"name":"foo bar","created_at":"2011-03-05T02:36:03Z","code":"1234","updated_at":"2011-03-05T02:36:03Z","id":1},{"name":"4321 bar foo","created_at":"2011-03-05T13:28:27Z","code":"4321","updated_at":"2011-03-05T13:28:27Z","id":2}]

**Comment by anibal** [comment]
I can try to put together an HTML page to reproduce the error, but it is a Rails app using Backbone.js and Coffeescript.

**Comment by twigkit** [comment]
No that's fine, I'll build a rough one from the info you've given me.

**Comment by twigkit** [comment]
You were right! Firefox escapes all attribute values, so the regex was not replacing these. Worked fine in other browsers. This is now fixed in master branch. Well spotted, thanks for reporting this!

**Comment by anibal** [comment]
Thanks you for you quick response :) I will update my test project from master and give it a try ASAP.
