### ISSUE TITLE
Dynamically created template

### ISSUE THREAD

**Issue by mavimo** [twigkit/tempo#15]
If i try to load template from remote source and add it into element tempo do not consider it:

```
  $(pages).each(function (i, page) {
  $.get('/layouts/' + page.layout + '/markup.html',
    function (data) {
      var p = document.createElement('div');
      p.innerHTML = data;
      // START ERROR
      // p.innerHTML = '<div>{{text}}</div>'
      var layout = Tempo.prepare(p);
      // p.innerHTML = ''
      // END ERROR!
      layout.starting();
      layout.render(data.layouts);
    });
});
```

is not possible generate tempalte without add it into page?

**Comment by twigkit** [comment]
I agree this would be a desirable feature. I'll have a look at this as soon as I can.

**Comment by mavimo** [comment]
Tks, i think can also be desiderable have a autoloader external page link:

<pre>
var url = "/template/layout.html";
var layout = Tempo.prepare(url, 'remote');
layout.starting();
layout.render(data);
</pre>

**Comment by iatek** [comment]
+1 for me on this feature. Thanks for the great JSON templating engine! I'm looking forward to playing with it.

**Comment by mrolafsson** [comment]
Hey guys, this feature is supported in 2.0 dev branch. You can see examples of it (external templates) in the solr example. Let me know how you get on!!

**Comment by iatek** [comment]
Thanks.. looking forward to trying it out
