### ISSUE TITLE
Make tag/variable syntax ({{...}}) configurable

### ISSUE THREAD

**Issue by twigkit** [twigkit/tempo#16]

**Comment by Terr** [comment]
Did this make it into the 1.5 release?

**Comment by mrolafsson** [comment]
Hey! Sorry no, I left it out because I didn't get any feedback on it. All I did was change the tag syntax for template tags. Sorry was this important to you? It's not a tricky one, just didn't want to risk errors.

**Comment by Terr** [comment]
Tempo is a bit difficult to use in Django (and Jinja2) templates, because they use the {{ ... }} syntax as well. It's possible to work around it, but it would make life easier if it was configurable to <? ... ?>, for nostalgic reasons ;)

It would be great if the option could still be added. Any in case, I'll be sure to give feedback on issues in the future :)

**Comment by mrolafsson** [comment]
Yeah sure, I had anticipated this to be an issue. Leave it with me and I'll see if I can quickly squeeze it in :) Thanks for your support.

**Comment by twigkit** [comment]
I've committed a first stab at this to the 'dev' branch. Can you try it out?

// It splits the overridden braces down the middle to create left/right
Tempo.prepare('nested-marx-brothers', {'var_braces': '::::', 'tag_braces: '////'}).render(data);

**Comment by Terr** [comment]
That was fast! I'll try it out this evening :)

**Comment by Terr** [comment]
I've tested out several var and tag braces in Firefox 4 and most worked out fine. Only PHP-like tags (<? ?>) didn't work, but I guess those are cursed ;)

**Comment by mrolafsson** [comment]
They probably work if you escape them for the regex: \<\?\?\> (maybe you don't even need to escape the <>)

**Comment by Terr** [comment]
I've tried escaping, but it didn't work. Maybe it's picked up as a HTML tag by the DOM?

**Comment by mrolafsson** [comment]
Hmmm right, yeah ok, weird. I'll do some testing tomorrow. Thanks for all your help.

**Comment by twigkit** [comment]
I'm afraid you're right. Browser seems to strip out the markup. But these work alright it seems:

```
Tempo.prepare('nested-marx-brothers', {'var_braces': '\\[\\[\\]\\]'}).render(data);
Tempo.prepare('complex-marx-brothers', {'tag_braces': '\\[\\?\\?\\]'}).render(data);
```

I haven't spotted any problems relating to this change.

**Comment by Terr** [comment]
These type of tags will do just fine. Thanks for the change, it's really appreciated :)

**Comment by twigkit** [comment]
No worries, thanks for your support. Please let me know if you spot any issues, the change was a 'substantial' one :) I'll probably do a bit more testing and then add this to master as a '1.6'.
