### ISSUE TITLE
Doesn't work with PrototypeJS :(

### ISSUE THREAD

**Issue by jamsi** [twigkit/tempo#18]
Adding the prototype JS library to the twitter example produces the following error;

Uncaught TypeError: Object function each(iterator, context) {
    var index = 0;
    try {
      this._each(function(value) {
        iterator.call(context, value, index++);
      });
    } catch (e) {
      if (e != $break) throw e;
    }
    return this;
  } has no method 'handler'

**Comment by mrolafsson** [comment]
Did you remove the jQuery references and swap out with Prototype code?

**Comment by willcannings** [comment]
The issue is around line 285 in the un-minified code. Change the tags loop to something like:

for(var p = 0, c = renderer.tags.length; p < c; p++)

rather than

for(var p in renderer.tags)

Which will fail in prototype because it adds properties to arrays.

**Comment by mrolafsson** [comment]
Thanks Will, yeah don't know why this wasn't a proper array iteration!! Can you guys see if this fixes your issue: https://github.com/twigkit/tempo/raw/master/tempo.js

Thanks for your help!!!

**Comment by willcannings** [comment]
Sure does, thanks!

**Comment by jamsi** [comment]
Yippee. Thanks William.
