### ISSUE TITLE
Problem with pipe (|) in replace filter

### ISSUE THREAD

**Issue by ghost** [twigkit/tempo#27]
I ran into another issue this morning: I was trying to use tempo on a twitter feed and created a regular expression to look for the URLs within the text of the feed.  My original expression had (http|https) to look for the token http or https; however, when Tempo was processing the filter, it split the regEx in two when it was performing the split for filter chaining.  I found a workaround by just removing the pipe and limitting the expression to just http.

**Comment by twigkit** [comment]
Thanks for reporting this, it's now fixed in the dev branch, soon to become 1.5.
