### ISSUE TITLE
[suggestion] Making tempo compatible for xhtml5 strict markup

### ISSUE THREAD

**Issue by bzerangue** [twigkit/tempo#30]
It would be nice if tempo could also work those who prefer using xhtml5 strict type markup, so instead of just having it work with a "naked" attribute data-template...

`<li class="row" data-template style="display: none;">`

that it also could work for those who want to use more xhtml-type strict markup like so...

`<li class="row" data-template="data-template" style="display: none;">`

Is that possible?

This is a wonderful application. Thanks for making it available.

**Comment by twigkit** [comment]
Hi! Thanks for reporting this, yes it's an excellent point. I've validated the problem and resolved in the 'dev' branch which will become 1.5.

**Comment by bzerangue** [comment]
Wow! Thanks so much! Very cool application by the way!!!

**Comment by twigkit** [comment]
Thanks man :) Really appreciate your input.
