### ISSUE TITLE
Trouble with multiple level nesting of data-templates

### ISSUE THREAD

**Issue by balajirrao** [twigkit/tempo#34]
I noticed that tempo doesn't seem to handle multiple levels of nesting of templates, especially when data-template names are identical across levels. When I used distinct name for each level of data-template, it seemed to work fine.

Example : 
[ { "body" : "1", "children" : [ { "body" : "11", "children" : [ { "body" : "111", "children" : [  ] } ] }, { "body" : "12", "children" : [ { "body" : "121", "children" : [  ] }, { "body" : "122", "children" : [  ] }, { "body" : "123", "children" : [  ] } ] }, { "body" : "13", "children" : [ { "body" : "131", "children" : [  ] }, { "body" : "132", "children" : [  ] }, { "body" : "133", "children" : [  ] } ] } ] }, { "body" : "2", "children" : [ { "body" : "21", "children" : [ { "body" : "211", "children" : [  ] }, { "body" : "212", "children" : [  ] } ] }, { "body" : "22", "children" : [ { "body" : "221", "children" : [  ] }, { "body" : "222", "children" : [  ] } ] } ] }, { "body" : "3", "children" : [ { "body" : "31", "children" : [  ] }, { "body" : "32", "children" : [ { "body" : "321", "children" : [  ] }, { "body" : "322", "children" : [  ] } ] }, { "body" : "33", "children" : [  ] }, { "body" : "34", "children" : [ { "body" : "341", "children" : [  ] } ] } ] }, { "body" : "4", "children" : [ { "body" : "41", "children" : [  ] }, { "body" : "42", "children" : [ { "body" : "421", "children" : [  ] } ] }, { "body" : "42", "children" : [  ] }, { "body" : "43", "children" : [  ] } ] } ]

**Comment by mrolafsson** [comment]
Hey, yes I noticed this issue now that I'm working on 2.0 and doing deeper nesting + external templates. I think I have this solved in the dev branch so will look at patching! Thanks for reporting!

**Comment by mrolafsson** [comment]
This is now fixed in dev-2.0 branch!
