### ISSUE TITLE
Parsing data skips first record

### ISSUE THREAD

**Issue by appsinteractive** [twigkit/tempo#37]
I am going thru the example and my person code and the first row is skipped. I've been looking for this type of project for sometime and could really use it in a current project i'm working on. Any ideas?

Again the sample code on you site produces the following results for me vs what you have as the example render.

Results:
-Chico Marx
---Papa Romani

-Harpo Marx
--Stage Door Canteen

-Groucho Marx
--Mr. Music
--Double Dynamite

-Gummo Marx

-Zeppo Marx
-A Kiss in the Dark

**Comment by michapixel** [comment]
I'm having the same Issues.

**Comment by basicxman** [comment]
I can confirm this too, it will skip the first record of `solo_endeavours` when there are multiple records.

**Comment by mrolafsson** [comment]
Hey guys. Yes sorry, this is a strange issue with 1.6. I've fixed in '1.7' and in the dev branch. I'll push 1.7 today! thanks for letting me know...I didn't get any notification from Github.

**Comment by mrolafsson** [comment]
This issue is resolved in v1.7
