### ISSUE TITLE
Should be able to do rendering on any HTML Tag attribute

### ISSUE THREAD

**Issue by josephhealy** [twigkit/tempo#39]
See http://jsfiddle.net/extcontact/dM3qf/5/

**Comment by mrolafsson** [comment]
It can render any tag attribute within the body of the template, this refers purely to the data-template element itself.

**Comment by josephhealy** [comment]
No I'm confused. If that were the case then shouldn't
http://jsfiddle.net/extcontact/dM3qf/5/ work...?

**Comment by mrolafsson** [comment]
No it shouldn't. The onclick attribute is on the data-template element, where only id and class attributes are rendered/populated by Tempo. If the data-template was on the parent the example you posted would work.

**Comment by josephhealy** [comment]
Yes, I figured that out and just updated the issue - why can't you render
any attribute on an element with the data-template attribute?

**Comment by mrolafsson** [comment]
I can, it's just not what version 1.6 did by default.

**Comment by mrolafsson** [comment]
Fixed in 1.7.
