### ISSUE TITLE
If a data record doesn't match any template element, the template is not output

### ISSUE THREAD

**Issue by josephhealy** [twigkit/tempo#40]
If I have three JSON records to apply to a template and one of them doesn't have rendering match within the template then the template is not output for any of the records - it should output the two records that did have rendering matches.

See http://jsfiddle.net/extcontact/D29U8/3/

If you remove the second JSON record the template will be output, otherwise it won't...it should be output for the two records that have rendering matches.

**Comment by mrolafsson** [comment]
If no default template is defined, then records without a conditional template will not be output.

**Comment by josephhealy** [comment]
In the code I linked to above, two of the three records do have conditional templates, but are still not output because the third one doesn't.

**Comment by mrolafsson** [comment]
This is using 1.7 and your code: http://jsfiddle.net/5XqWK/1/

**Comment by josephhealy** [comment]
Cool, thanks.

https://raw.github.com/twigkit/tempo/v1.7/tempo.js

Having the url format for each version is helpful...
