### ISSUE TITLE
Last filter gets applied twice when chaining filters.

### ISSUE THREAD

**Issue by Ziao** [twigkit/tempo#49]
Something appears to be broken in the Regex generated in _replaceVariables (var filterSplitter). When trying to split the arguments it will output an array with 3 elements while only 2 filters were specified. This results in the last filter being applied twice.

This wouldn't really be a problem in most (default) filters, but for one of my filters the effects are devastating.
I fixed this the quick and dirt way by doing replacing

```
    var filterSplitter = new RegExp('\\|[ ]?(?=' + utils.memberRegex(renderer.filters) + ')', 'g');
```

with

```
    var filterSplitter = "|";
```

This seems to give no further(!) problems, aside from the other issue that states trying to use a pipe in the replace filter makes things explode (or split? :p).

Thanks for building this, loving it so far ;)
One thing I'd like to add is to make it possible to easily create filters externally.

**Comment by mrolafsson** [comment]
Sorry Ziao for the late reply. Let me have  a look at this in 2.0.

**Comment by mrolafsson** [comment]
I can't reproduce this issue in 2.0.

**Comment by mrolafsson** [comment]
I agree, it's on the agenda to be able to easily plug in filters.
