### ISSUE TITLE
can not get _tempo.index using tempo.min.js(packed version)?

### ISSUE THREAD

**Issue by tomheng** [twigkit/tempo#50]
I can not get "_tempo.index" in tempate  while using tempo.min.js(packed version), but i can do that with tempo.js(uncompressed version)?

is it something wrong happened when compressing?

**Comment by sull** [comment]
ditto. so i just compressed the full version myself. but yeah, fyi to update your download.

**Comment by mrolafsson** [comment]
Sorry this should be up to date now.
