### ISSUE TITLE
Capitalize

### ISSUE THREAD

**Issue by juanmadryn** [twigkit/tempo#53]
We don't find a way to capitalize every word in a string through any filter, so we created a 'capitalize' filter:

'capitalize': function(value, args){
                return value.replace( /(^|\s)([a-z])/g , function(m,p1,p2){return p1+p2.toUpperCase();});
}

**Comment by mrolafsson** [comment]
Sorry I didn't see this issue! Thanks for the addition - I will add this to 2.0.

**Comment by mrolafsson** [comment]
Added a 'titlecase' filter with blacklist support which ignores first words and preserves uppercased words: http://jsfiddle.net/gh/get/jquery/1.8/twigkit/tempo/tree/dev-2.0/examples/filters/titlecase/

**Comment by mrolafsson** [comment]
http://jsfiddle.net/gh/get/jquery/1.8/twigkit/tempo/tree/dev-2.0/examples/fiddles/filters/titlecase/
