### ISSUE TITLE
nested templates in separate calls..?

### ISSUE THREAD

**Issue by dmeikle** [twigkit/tempo#54]
first of all, I LOVE tempo...

here's my question - I have a list of members that are being rendered to the page using tempo, in a table style format (each row is a member name, address, contact info..).
I would like to be able to click on a user and make a 2nd ajax call to the server, inserting information beneath the selected user with a list of documents that are associated to the user:

user #1       telephone          address     email  <-- these are drawn during initial page render
user #2       telephone          address     email
  --    document #1  <-- user #2 is clicked, and a separate call is made to populate this information
 --     document #2
user #3       telephone          address     email
user #4       telephone          address     email

I've tried using a nested template but it gets rendered during the initial page draw and the tags are then removed... is tempo set up for this and I just need to find the right sample code..?

**Comment by rkoberg** [comment]
This feature was just added in dev-2.0 branch - checkout https://github.com/twigkit/tempo/issues/55
