### ISSUE TITLE
data-src not replacing src in data-template-for

### ISSUE THREAD

**Issue by rkoberg** [twigkit/tempo#57]
This is not working in the up-to-date dev-2.0 branch:

&lt;div class="total-reads" data-template-for="total_reads">
  &lt;img alt="{{num}}" src="/placehold.png" data-src="{{url}}"/>
&lt;/div>

The src attribute is not getting replaced.

**Comment by mrolafsson** [comment]
I was able to reproduce this! I've committed what I think is a fix to this problem - would you be able to test it in IE 6-7 as well?

**Comment by rkoberg** [comment]
Just seeing this now. I used a workaround (CSS images) and will try to get to testing (very busy, just launching one site and another is due in two weeks)

**Comment by mrolafsson** [comment]
Good luck with your launch!
