### ISSUE TITLE
IE8 problem with the 'in' method/function

### ISSUE THREAD

**Issue by rkoberg** [twigkit/tempo#58]
I needed to use quotes on the Renderer.prototype's 'in' method to get Tempo to work in IE8. On line 616 in Tempo.js:

```
    "in":function (target) {
        if (target !== undefined) {
            this.templates.container = utils.container(target);
        }

        return this;
    },
```

Otherwise, Tempo is broken in IE8.

**Comment by mrolafsson** [comment]
Ah was that the problem. Yeah I think you maybe using a slightly outdated version there because I had renamed that to "into" (2.0 branch - no dev anymore) mainly because I thought maybe 'in' was a reserved/risky word. I do prefer 'in' so is it cool to just put quotes around the method names?

**Comment by rkoberg** [comment]
It does work, but I also need to this when calling it, so probably not optimal:

student_template['in']($container).render(templ_array);

**Comment by mrolafsson** [comment]
Yeah I thought so - try the newer version. The documentation is also almost updated on the beta site: http://tempojs.com/2.0/

**Comment by mrolafsson** [comment]
Can you confirm that this worked for you?

**Comment by rkoberg** [comment]
Haven't had a chance to yet, but will. In the middle of launching a couple
of large sites...

**Comment by rkoberg** [comment]
I can confirm into works in IE8. Sorry it took so long.

**Comment by mrolafsson** [comment]
No problem Rob!
