### ISSUE TITLE
TempoJS Not Working with collapsible panel in Jquery Mobile.

### ISSUE THREAD

**Issue by darmie** [twigkit/tempo#60]
After applying Tempo JS, it seemed to have worked as it should but the collapsible panel UI provided by Jquery mobile stopped working.

**Comment by mrolafsson** [comment]
If you provide a runnable jsFiddle I'll have a look for you. Best, Stefan

**Comment by darmie** [comment]
Ok. i'll do that soon, when i get on my pc. 
Sent from my BlackBerry wireless device from MTN

-----Original Message-----

**Comment by difrnt** [comment]
@darmie this seems to work http://jsfiddle.net/GmAqf/
