### ISSUE TITLE
.clear() not working.

### ISSUE THREAD

**Issue by i0n** [twigkit/tempo#61]
Hi there!

I have been using Tempo and it's been pretty easy to use, until I hit a snag this afternoon.

I have a table where the row has the data-template attribute.
I am longpolling via Ajax and I want to clear the template before repopulating with the new data.
calling clear() does nothing as far as I can see. I end up with duplicate entries in the table (1 instance of each row for each successful JSON response)
I have tried using version 1.8 and the 2.0 branch and both do not clear the existing records.
Is this a known bug?

**Comment by mrolafsson** [comment]
Hi there!! I was under the impression that this was fixed? How does this render for you: http://tempojs.com/2.0/examples/table
It should use the underlying clear method, and if memory serves me replaces one set of data with another. If you send me a jsFiddle with your example then I'm happy to try and fix with you!

**Comment by mrolafsson** [comment]
I take it you're aware of updated documentation here: http://tempojs.com/2.0/

**Comment by i0n** [comment]
The table you sent me renders fine, but I don't see any calls to .clear() in the code?
I've been fiddling around with this and it seems that the problem is that re-rendering the template happens before the template can be cleared and so both versions end up on the screen. What is required is a callback for when the template has been cleared. It would be great to be able to do:

tempovar.clear( function() {
    tempovar.render(data);
});

**Comment by mrolafsson** [comment]
Internally render() calls the clear() method. I've now added events for both before and after clear() if that helps? http://tempojs.com/2.0/#preprocessing

**Comment by mrolafsson** [comment]
This should work now! Reopen if it does not fix your problem! Thanks.
