### ISSUE TITLE
Can you give More examples.

### ISSUE THREAD

**Issue by BMeridian** [twigkit/tempo#62]
How about using the mark bros example on one page. 
Yahoo finance example?

Any example using KOjs or AngularJs.

**Comment by mrolafsson** [comment]
Hey! Can you describe what sort of demo you would like to see? No I have not tried these libraries but feel free to send examples my way!

**Comment by BMeridian** [comment]
I like this framework, thanks for it! 

EMPHASIS THAT TEMPO NEEDS DATA IN ARRAY FORMAT. ;-)

1: Usings Marks Bros. data, Create the example from the home page as a standalone HTML page. 
The data is not valid json, It uses single ' vs double " .

2: Load the data from local file using JQuery [ $.getJSON('./marks.json', function()... ).]  
The example you show so far are web based calls, they dont allow for local testing on local data. 

3: Load the data from SQLite db / MySQL db, The same data.  Please no PHP, python or nodeJS.  Using Jquery Ajax methods.  If the data for "solo " works causes a problem. Change data set.
But please show how to use template with database (local). 
1.  Anything streaming. Idea for streaming: Two twitter feeds, beer and pizza. combine on page. 
   Have template display one topic in light blue, another topic in light yellow. In one div in one table. 
   An extension to that would be a third local file with data,  combined with other two showing  speed 
   flexible of template. 
2.  Anything that shows, AJAX refreshes and template interaction. A couple of AJAX hooks on 
   the page. 

I'll think about KnockoutJS examples.  Thanks again!!!

**Comment by difrnt** [comment]
@SlyOne you can definitally load data from a local file, that is how I initially started testing the framework.

``` javascript
var jsonFILE = 'twit.json';
            var twitter = Tempo.prepare('tweets').notify(function(event) {
                if (event.type === TempoEvent.Types.RENDER_STARTING || event.type === TempoEvent.Types.RENDER_COMPLETE) {
                    $('ol').toggleClass('loading');
                }
            });
            twitter.starting();
            $.ajax({
              mimeType: 'application/json',
              dataType:'json',
              url: jsonFILE,
              success: function(data) {
                  twitter.render(data.results);
              }
            });
```

**Comment by mrolafsson** [comment]
Hey guys - yeah it would be great to get more demos up there, feel free to clone and add some more and send me a pull request. The data does not need to be an array, the `data-from-map` parameter allows you to iterate associative arrays (objects) too: http://tempojs.com/2.0/#data-from-map

**Comment by BMeridian** [comment]
Can you use 'plunker' for the examples. its self contained, better than
JSFiddle.

**Comment by mrolafsson** [comment]
The examples are just in the /examples folder. I'm not going to create fiddles for each one I think - too much overhead to keep updated. Github/jsFiddle integration seemed a bit flaky. Can we close this issue now?

**Comment by BMeridian** [comment]
close it

**Comment by BMeridian** [comment]
Actually, Create them once and deprecate.

**Comment by mrolafsson** [comment]
Sure I will keep that in mind! I'll try plnkr as well.

**Comment by BMeridian** [comment]
Thanks for the examples!!! It makes using the lib alot easier and shows that separation very well!

**Comment by mrolafsson** [comment]
Sorry I have not had a lot of chance to work on Tempo lately - but the 3.0 branch is looking very promising. Much faster, 100% test coverage etc.

**Comment by sqram** [comment]
Can't wait.

**Comment by mrolafsson** [comment]
Are you guys still keen on using Tempo?

**Comment by sqram** [comment]
Yes. I am about to use it in production at the company I work, for landing pages mailed out to tens of thousands :)
