### ISSUE TITLE
Multiple (non-nested) data-template-for not rendered

### ISSUE THREAD

**Issue by difrnt** [twigkit/tempo#64]
I've created a jsfiddle example just incase I'm doing something wrong.
http://jsfiddle.net/5fXNy/1/

Thanks!

**Comment by rkoberg** [comment]
I think you need to pass arrays of object(s) not an object to the templates
and nested templates.

Check out the examples: http://tempojs.com/2.0/

At times, I have needed to reorganize the JSON sent from the server on the
client before rendering the template.

**Comment by mrolafsson** [comment]
Hey guys, you highlighted an important piece of missing documentation in 2.0. You can iterate associative arrays using the `data-from-map` attribute on a data-template: http://tempojs.com/2.0/#data-from-map
The data example can be rendered using that and a slightly different html: http://jsfiddle.net/mr_olafsson/pJq6a/

**Comment by mrolafsson** [comment]
Closing this - if you find this does not fix your issue or you have any further comments just reopen.

**Comment by difrnt** [comment]
@mrolafsson Any thoughts on why this one isn't working?

http://jsfiddle.net/pJq6a/2/

**Update:**
Looks like this one works, just had to change up the HTML a little bit:

http://jsfiddle.net/pJq6a/3/

**Comment by mrolafsson** [comment]
Yes, this is a little bit tricky - but basically the repeating nested elements need to have a container it seems: http://jsfiddle.net/mr_olafsson/n46Cz/ Semantically I would put these in a list and in that case it will work as expected. Otherwise these are separate rendering calls, the second of which clears the container.
