### ISSUE TITLE
"Why doesn't this work?" Or "The examples are not that great"

### ISSUE THREAD

**Issue by onedayitwillmake** [twigkit/tempo#66]
Hi,

This library seems great, it's really off to a great start and I love the idea of it.
However it seems a trivial example either A does not work, or B there is not much documentation on how to accomplish it.

Currently the examples do too much at once, a couple of more basic examples would really go a long way.

Here is a simple example I expected to work:
http://onedayitwillmake.com/_ignore/tempotest/

**Comment by mrolafsson** [comment]
Your example seems to work fine? I would have just put `display: none;` on the template to prevent blinking. The examples folder has lots of test cases. What kind of examples would work better for you?

**Comment by mrolafsson** [comment]
You can now add your own error handling:

```
Tempo.prepare('list').errors(function (err) {
    console.log('Whoa! something happened!');
    console.log(err);
}).render(data);
```
