### ISSUE TITLE
Rendering of null values not working everytime

### ISSUE THREAD

**Issue by hcapitaine** [twigkit/tempo#69]
Hello dev(s),

I found an issue with tempojJs versions 1.8 and 2.0, on Firefox 19 and maybe previous versions.

I use tempoJs to render an HTML template with inputs filled by data retrieved via an ajax call.
But sometimes when values are null it doesn't work.
So I did a test with a single input and a null value and it works.
So I did a test with multiple inputs and alternate null values and it fails, the 2 two lasts input contains the value "null".
Here is the json:

``` javascript
{
    "street1": "test1",
    "street2": "test2",
    "street3": "null",
    "street4": "null"
}
```

Here is the HTML:

``` html
<!DOCTYPE html>
<html>
<head>
<script src="http://code.jquery.com/jquery-1.9.0.js"></script>
<script src="./tempo.js" type="text/javascript"></script>

<script>
$(document).ready(function(){
    $.ajax({
       url: './result.json',
       success: function(data,textStatus,jqXHR){
           Tempo.prepare("myForm").render(data);
       },
       dataType: 'json'
    });
});

</script>
</head>
<body>
    <form id="myForm" data-template>
        <input name="streetName1" type="tel" value="{{street1 | default 'HCA'}}"/>
        <input name="streetName2" value="{{street2}}"/>
        <input name="streetName3" value="{{street3 | default 'HCA3'}}"/>
        <input name="streetName4" value="{{street4}}"/>

    </form>
</body>
</html>
```

I will try to give a look to find the bug but not sure to have time.

Thanks for your product

**Comment by mrolafsson** [comment]
Thanks for reporting this! I've done a quick test here but to me it looks like it behaves correctly: http://jsfiddle.net/mr_olafsson/njag9/

In the first test I iterate an array with objects and null objects (which are correctly skipped) and object with null members (which are correctly candidates for defaults). I then use your test (changing 'null' to null since otherwise they're just strings) and it behaves correctly. Can you confirm the same?

**Comment by hcapitaine** [comment]
You're right, I can't reproduce it for now, but I spent a day to make it work without succeeding. So sorry for disturbing you, I will open a new one if I manage to reproduce it. Keep doing such a great work.

**Comment by mrolafsson** [comment]
No problem - let me know if you get stuck and I'll have a look with you. You did notice that your example had nulls as strings? That's the only thing I changed in your example. Good luck with the project - and thanks for your support.

**Comment by hcapitaine** [comment]
Yeah you're right, but in my real case null was send back by resteasy so
null was not a string. Thanks for your great support.
