### ISSUE TITLE
Template.prepare being too grabby

### ISSUE THREAD

**Issue by meglorin** [twigkit/tempo#70]
This could be an implementation error, but things are not behaving as I would expect them too, so I am posting an issue.

The issue is that I have two templates in the same table structure.  The first, dt_investor_fundHistory, renders as expected while the second, dt_investor_totals, is removed from the DOM by prepare (as expected) but isn't rendered.  If I break them up into separate tables, they both render.

Fiddle: http://jsfiddle.net/mgriffith/enNws/

Template:

<pre>
&lt;div class="accordion well" id="content-accordion" data-template&gt;
...
&lt;table class="table table-striped table-condensed table-bordered"&gt;
    &lt;thead&gt;
        &lt;tr&gt;
            &lt;th class="txtl"&gt;Fund&lt;/th&gt;
            &lt;th&gt;Year&lt;/th&gt;
            &lt;th&gt;Cmmt&lt;br&gt;(M)&lt;/th&gt;
            &lt;th&gt;Cont&lt;br&gt;(M)&lt;/th&gt;
            &lt;th&gt;Rem&lt;br&gt;(M)&lt;/th&gt;
            &lt;th&gt;Dist&lt;br&gt;(M)&lt;/th&gt;
            &lt;th&gt;Mult&lt;br&gt;(M)&lt;/th&gt;
            &lt;th&gt;IRR&lt;br&gt;%&lt;/th&gt;
            &lt;th&gt;NAV&lt;br&gt;(M)&lt;/th&gt;
        &lt;/tr&gt;
    &lt;/thead&gt;
    &lt;tbody&gt;
        &lt;tr data-template-for="dt_investor_fundHistory"&gt;
            &lt;td&gt;{{ FundPtnr }}{% if status %}&lt;br&gt;({{ status }}){% endif %}&lt;/td&gt;
            &lt;td&gt;{{ Year }}&lt;/td&gt;
            &lt;td class="numeric"&gt;{{ Commit }}&lt;/td&gt;
            &lt;td class="numeric"&gt;{{ Contrib }}&lt;/td&gt;
            &lt;td class="numeric"&gt;{{ Remaining }}&lt;/td&gt;
            &lt;td class="numeric"&gt;{{ Distrib }}&lt;/td&gt;
            &lt;td class="numeric"&gt;{{ Multiple }}&lt;/td&gt;
            &lt;td class="numeric"&gt;{{ IRR }}&lt;/td&gt;
            &lt;td class="numeric"&gt;{{ NAV }}&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr class="success" data-template-for="dt_investor_totals"&gt;
            &lt;td colspan="2"&gt;Totals&lt;/td&gt;
            &lt;td class="numeric"&gt;{{ Commit }}&lt;/td&gt;
            &lt;td class="numeric"&gt;{{ Contrib }}&lt;/td&gt;
            &lt;td class="numeric"&gt;{{ Remaining }}&lt;/td&gt;
            &lt;td class="numeric"&gt;{{ Distrib }}&lt;/td&gt;
            &lt;td class="numeric"&gt;{{ Multiple }}&lt;/td&gt;
            &lt;td class="numeric"&gt;{{ IRR }}&lt;/td&gt;
            &lt;td class="numeric"&gt;{{ NAV }}&lt;/td&gt;
        &lt;/tr&gt;
    &lt;/tbody&gt;
&lt;/table&gt;
...
&lt;/div&gt;
</pre>

Structure (edited for simplicity):

<pre>
{
 "results": [
  {
   "id": "RELID00001",
   "dt_investor_fundHistory": [
     {
       "FundPtnr": "RF2 - Investor A",
       "status": "Committed",
       "Year": "2002",
       "Commit": "40.00",
       "Contrib": "",
       "Remaining": "40.00",
       "Distrib": "",
       "Multiple": "",
       "IRR": "",
       "NAV": ""
     },
   ],
   "dt_investor_totals": [
     {
       "Commit": "325.00",
       "Contrib": "20.78",
       "Remaining": "304.22",
       "Distrib": "27.65",
       "Multiple": "15.97",
       "IRR": "15.58",
       "NAV": "7.50"
     }
   ],
  }
 ]
}
</pre>

**Comment by mrolafsson** [comment]
I think the problem there is that the nested templates do not have a parent container; so when the first one is parsed it removes the other. Can you not put `dt_investor_totals` in `tfoot`? You could also tackle this by parsing the `dt_investor_totals` from a different location and use the `into` method to append it to the main container afterwards?

**Comment by meglorin** [comment]
tfoot is a nicely semantic way to solve the problem.  I tried it out in the fiddle and it works like a charm.  Thanks a ton for the help.  Closing this ticket.

**Comment by mrolafsson** [comment]
You haven't noticed what we're seeing in #71 ?
