### ISSUE TITLE
All Nested Tables in IE don't Render

### ISSUE THREAD

**Issue by difrnt** [twigkit/tempo#71]
In Chrome and Firefox this renders fine, however in IE one of the tables renders and the other does not. 

Example here:
http://jsfiddle.net/GT4LP/

**Comment by difrnt** [comment]
I've tracked it down to this:

``` javascript
            if (navigator.appVersion.indexOf("MSIE") > -1 && utils.equalsIgnoreCase(template.tagName, 'tr')) {
                // Wrapping to get around read-only innerHTML
                var el = _window.document.createElement('div');
                el.innerHTML = '<table><tbody>' + html + '</tbody></table>';
                var depth = 3;
                while (depth--) {
                    el = el.lastChild;
                }
                el.setAttribute('data-template', '');
                return el;
            } else {
                // No need to wrap
                template.innerHTML = html;
                return template;
            }
```

If I comment this out and just use:

``` javascript
template.innerHTML = html;
                return template;
```

all works fine, however uncommented breaks.

**Comment by mrolafsson** [comment]
Can you see what the error is? Does IE tell you? Normally it needs to wrap TRs for IE.

**Comment by difrnt** [comment]
That's the thing, no errors are given, even with the new .error option.

**Comment by difrnt** [comment]
UPDATE: IE10 works great with my "fix", IE9 breaks and doesn't seem to render the table correctly, just the values.

**Comment by mrolafsson** [comment]
I think you're on the right track - there is something maybe in that table wrapper - I'm not able to look at it just now so I really appreciate your debugging.

**Comment by mrolafsson** [comment]
Is this guy not dealing with similar stuff: https://github.com/twigkit/tempo/issues/70

**Comment by difrnt** [comment]
I'd bet that the same piece of code is the culprit.

**Comment by difrnt** [comment]
As a "workaround" to this problem I've replaced the getElement function with:

``` javascript
getElement: function (template, html) {
            if (navigator.appVersion.indexOf("MSIE") > -1 && utils.equalsIgnoreCase(template.tagName, 'tr')) {
                var txt = _window.document.createTextNode('<tr>' + html + '</tr>');
                return txt;
            } else {
                // No need to wrap
                template.innerHTML = html;
                return template;
            }
        },
```

And then on RENDER_COMPLETE I call this to render the escaped HTML:

``` javascript
                $("tbody").each(
                    function(){
                        var txt = $(this).text();
                        $(this).html(unescape(txt));
                    });
```

By no means is this a proper fix, it just works for what I need it to work for. :+1: 

**_UPDATE**_
I lied, it get's me started but by no means is it a fix, it only fixes some tables. I do believe that fieldsets are affected as well, this may be more widespread than I initially thought.

**Comment by philllies** [comment]
Just wondering: is this issue being worked on?
It would be really great if nested tables rendered properly down to IE7.

**Comment by difrnt** [comment]
@philllies you can try my "fix" it works for tables but I'm having problems with other elements of my design, not sure if it's my code or another "bug".

**Comment by mrolafsson** [comment]
Sorry I haven't had a lot of time to look at this lately - I will revisit this today.

**Comment by mrolafsson** [comment]
I'm not quite sure what the problem is guys, I've created an example here with nested templates rendering tables and table rows: http://jsfiddle.net/mr_olafsson/nKkcF/
The only issue I can see when there is not a container around the nested template?

**Comment by mrolafsson** [comment]
OK so the difference is multiple tables it seems!

**Comment by mrolafsson** [comment]
No that also works for me - there must be something subtle in those templates. This works fine for me in IE 8.0:

```
<!-- Import Tempo -->
<script type="text/javascript" src="../tempo.js"></script>

<!-- This example uses jQuery's ajax() method to retrieve data from Solr -->
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
<script>
    var data = [
        {
            "title": "Places",
            "details": [
                {
                    "places": [
                        {
                            "country": "USA",
                            "date": "20140101"
                        },
                        {
                            "country": "Germany",
                            "date": "20140102"
                        },
                        {
                            "country": "Germany2",
                            "date": "20140102"
                        },
                        {
                            "country": "Germany3",
                            "date": "20140102"
                        },
                        {
                            "country": "Germany4",
                            "date": "20140102"
                        },
                        {
                            "country": "Germany5",
                            "date": "20140102"
                        },
                        {
                            "country": "Germany6",
                            "date": "20140102"
                        },
                        {
                            "country": "Germany7",
                            "date": "20140102"
                        }
                    ]
                }
            ]
        },
            {
            "title": "Places",
            "details": [
                {
                    "places": [
                        {
                            "country": "USA - 2",
                            "date": "20140101"
                        },
                        {
                            "country": "Germany - 2",
                            "date": "20140102"
                        },
                        {
                            "country": "Germany2 - 2",
                            "date": "20140102"
                        },
                        {
                            "country": "Germany3 - 2",
                            "date": "20140102"
                        },
                        {
                            "country": "Germany4 - 2",
                            "date": "20140102"
                        },
                        {
                            "country": "Germany5 - 2",
                            "date": "20140102"
                        },
                        {
                            "country": "Germany6 - 2",
                            "date": "20140102"
                        },
                        {
                            "country": "Germany7 - 2",
                            "date": "20140102"
                        }
                    ]
                }
            ]
        }
    ];

    $(document).ready(function () {
        Tempo.prepare('template').render(data);
    });
</script>
<div id="template" data-template>
    <h1>{{title}}</h1>

    <div>
        <div data-template-for="details">
            <table>
                <thead>
                <tr>
                    <th>Country Name</th>
                    <th>Date</th>
                </tr>
                </thead>
                <tbody>
                <tr data-template-for="places">
                    <td>{{country}}</td>
                    <td>{{date}}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
```

**Comment by mrolafsson** [comment]
Is it possibly an issue in IE < 8.0?

**Comment by philllies** [comment]
Thanks for looking into this issue.
It seems to work in IE9 if `data-template` is NOT set on the `<table>` but on a wrapper `<div>`. However, in my case, it messed-up the markup so that the `thead` was dislayed below the `tbody`.

IE7 crashes completely and IE8 only partially renders my table.

**Comment by mrolafsson** [comment]
Yes it's really strange - yeah a key aspect of nested templates (and this may be missing from the docs) is that they need a container around them (like `<ul>` which is also more semantic). There must be something strange going on here - I would really appreciate your help debugging this, e.g. by checking which elements are crashing IE < 8.0 because I'm a bit strapped for time today - but I will try and fix this!

**Comment by philllies** [comment]
Unfortunately i can't invest more time into this right now, I really need to get my project done. So i guess I have to find some other solution.

Anyways, thanks for looking into this. I might investigate a little more if I have a few minutes to spare.

**Comment by mrolafsson** [comment]
I understand - good luck!

**Comment by philllies** [comment]
OK, I managed to postpone the deadline a little, so if you manage to fix this bug somehow, I'd be most grateful.
I believe that rendering tables is such a common task for template engines, this really should work.

I will also try my best to track the problems down.

**Comment by mrolafsson** [comment]
Hi! Are you still using Tempo? Would you be interested in it's continued development?

**Comment by philllies** [comment]
Hey!
No I'm no longer using Tempo, but thanks for asking.

Cheers,
Phil

**Comment by mrolafsson** [comment]
Hi, thanks for getting back to me. Again, sorry I wasn't able to support you quicker at the time. I appreciate your feedback. Best of luck! Stefan
