### ISSUE TITLE
Conditional templates should not require a fallback

### ISSUE THREAD

**Issue by tylertate** [twigkit/tempo#72]
When using conditional templates, a fallback currently has to be provided in order for the templates to be rendered correctly — even if the fallback template isn't actually used. For example, if only the below conditional templates are specified, they are not rendered correctly:

```
<tr data-template data-if-id="1">
    <td>First one! {{id}}</td>
    <td>{{nickname}}</td>
    <td>{{born}}</td>
</tr>
<tr data-template data-if-id="2">
    <td>Second one! {{id}}</td>
    <td>{{nickname}}</td>
    <td>{{born}}</td>
</tr>
```

If a fallback is provided, they do render:

```
<tr data-template data-if-id="1">
    <td>First one! {{id}}</td>
    <td>{{nickname}}</td>
    <td>{{born}}</td>
</tr>
<tr data-template data-if-id="2">
    <td>Second one! {{id}}</td>
    <td>{{nickname}}</td>
    <td>{{born}}</td>
</tr>
<tr data-template>
    <td>Fallback {{id}}</td>
    <td>{{nickname}}</td>
    <td>{{born}}</td>
</tr>
```

However, I would not expect a fallback template to be required. Here is a jsFiddle demonstrating the issue (try commenting out the fallback template): http://jsfiddle.net/bnyzA/1/

**Comment by tylertate** [comment]
This was tested using 2.0.

**Comment by mrolafsson** [comment]
Ah right - so by fallback you mean 'default' template - fallback is used when javascript is not enabled or there is a fatal error. Yeah to be honest I had not tried having no default template but I can fix this.

**Comment by mrolafsson** [comment]
Solved on master branch!
