### ISSUE TITLE
Too many template iterations

### ISSUE THREAD

**Issue by malpaso** [twigkit/tempo#75]
Hi,

I have the following JSON data.

```
[{"price":"5.0000","name":"Test Dry Dog Food","guid":"AC6D5C24-F4EC-38DB-A273-86681F2B64DC","id":"1","image_secondary":"","image_primary":"","image_thumbnail":""}]
```

A simple Tempo.prepare(id).render(data) with this JSON renders correctly, however when the data is returned from the server via ajax, it iterates 163 times on the above data.

The data response from the server (in Chrome Dev Tools) looks like this:

```
"[{\"price\":\"5.0000\",\"name\":\"Test Dry Dog Food\",\"guid\":\"AC6D5C24-F4EC-38DB-A273-86681F2B64DC\",\"id\":\"1\",\"image_secondary\":\"\",\"image_primary\":\"\",\"image_thumbnail\":\"\"}]" 
```

**Comment by difrnt** [comment]
Prior to re-rendering the object you may want to call the tempo .clear() function. It should do this automatically, but this should guarantee it's cleared.

Here's the example from the tempojs.com site:

``` javascript
Tempo.prepare('marx-brothers').render( data ).clear();
```

**Comment by malpaso** [comment]
Thx @difrnt  I actually figured out the error. I had to use $.parseJSON() on my return string, apologies for the bother.

**Comment by mrolafsson** [comment]
Thanks Matt for the help debugging - I really appreciate it!
