### ISSUE TITLE
Separating iterated elements - usage of _tempo.index in tag blocks

### ISSUE THREAD

**Issue by platan** [twigkit/tempo#77]
I would like to display array as a list of links, separated by comma, for example for 
`var data = [ ['Leonard','Marx'], ['Adolph','Marx'], ['Julius Henry','Marx'], ['Milton','Marx'], ['Herbert','Marx'] ];`
result should be 
"[Leonard Marx](), [Adolph Marx](), [Julius Henry Marx](), [Milton Marx](), [Herbert Marx]()"
This solution http://jsfiddle.net/YF5zc/2/ displays comma after last element and I want to avoid this. 
Is it possible tu use _tempo.index in template tag, to detect index of the iterated element? 
I imagine such a solution:

``````
<span id="marx-brothers">
    <span data-template>
        <a href="#">{{[0]}} {{[1]}}</a>{% if __._tempo.index < 4 %},{% endif %}
    </span>
</span>```
``````

**Comment by mrolafsson** [comment]
Yes, this is currently not possible but should be a very easy addition - good suggestion - I'll feedback ASAP.

**Comment by mrolafsson** [comment]
In latest master: https://github.com/twigkit/tempo/blob/master/tempo.min.js
You can use `_tempo.first` and `_tempo.last`.

**Comment by platan** [comment]
Thanks. But how can I use it for conditional rendering?

I would like to use `_tempo.last` in template tag:

```
<span id="marx-brothers">
    <span data-template>
        <a href="#">{{[0]}} {{[1]}}</a>{% if !_tempo.last %},{% endif %}
    </span>
</span>
```

EDIT: removed proposed solution using conditional template because it has no sense.  

Or maybe there is another option?

**Comment by mrolafsson** [comment]
Hi, I know it's very late to be picking this up now and apologise for not having responded to your issue. Are you still using Tempo?

**Comment by platan** [comment]
Hi. I'm no longer working on a project where Tempo was used, but the project is still using Tempo.

**Comment by mrolafsson** [comment]
OK great. Sorry I wasn't able to support you better at the time. Good luck with your project!
