### ISSUE TITLE
Conditional and HTML injection

### ISSUE THREAD

**Issue by TheCelavi** [twigkit/tempo#78]
M I missing something?

Is this possible:

{if (condtion)}
Some HTML code or string
{endif}

? I want to check for null, and if something is not null, to render some HTML, or not otherwise. 

Second issue, is this possible:

var sommeHTML = '<p>Text</p>'

and in template:

<div>{sommeHTML}</div>

To be rendered without escaping?

**Comment by mrolafsson** [comment]
Yes both should work: http://jsfiddle.net/mr_olafsson/CS3Yz/

**Comment by TheCelavi** [comment]
Thx - either i missed this in documentation or documentation needs to be slightly improved.

Thanks!!!
