### ISSUE TITLE
SyntaxError: missing ; before statement

### ISSUE THREAD

**Issue by platan** [twigkit/tempo#79]
I get such an error (Firefox 20.0) on JavaScript console: 
Error: SyntaxError: missing ; before statement
in something like this using Tempo 2.1: 

```
<img src="{{ id | prepend './thumbnails/'}}" onerror="this.onerror=null;this.src='{{type | prepend 'static/img/' | append '.png'}}';"  alt="[image]" />
```

Example:
http://jsfiddle.net/zxmc7/2/

**Comment by mrolafsson** [comment]
I do not get an error in 2.1 in Firefox. It is not really good practice to use templates in JS code, I would preprocess this as necessary before rendering or alternatively use the script injection: http://jsfiddle.net/mr_olafsson/jtHW3/

**Comment by platan** [comment]
Thanks for your prompt response! After using script injection previous error message gone. Now I get another error in web console, but it still works. 
_ReferenceError: __ is not defined
I attach screenshots of previous anc current errors. 
![a](https://f.cloud.github.com/assets/1526000/506542/eb09da8c-bd52-11e2-8151-f0211817505e.png)
![b](https://f.cloud.github.com/assets/1526000/506545/eea9387c-bd52-11e2-8906-11483e393f63.png)

**Comment by mrolafsson** [comment]
Does this work outside of Fiddle?

**Comment by mrolafsson** [comment]
Script probably gets evaluated by the browser before the js injection is done - at the end of the day it's not good policy to do this inline. I would set data- attributes and bind some event to elements with jQuery and use .attr() to get the stuff you need for the script.

**Comment by platan** [comment]
I've done it like you said, it works. Thank you for your help!
