### ISSUE TITLE
Add option to specify rendered CSS class instead of display: block

### ISSUE THREAD

**Issue by arsduo** [twigkit/tempo#8]
Hi,

Tempo looks fantastic, I'm excited to use it in my projects.  However, I know I'll need to generate inline-block elements dynamically for one site.  It would be great if I could pass in a CSS class to be applied to data templates once they're rendered; adding display: block could remain the fallback behavior if no class is provided.  That would give developers more control over how the content is rendered.

If you want, I'd be happy to implement this this week and submit a pull request.

Thanks!

Alex

**Comment by twigkit** [comment]
Hi Alex! Thanks for the great feedback. There is actually a tiny error in the documentation. We changed this behaviour just before launch. We actually don't put display: block; on the rendered output. All we do is remove display: none; if you put that on the template as a style (so that it will remain invisible even though the javascript hasn't loaded). So all you need to do is add display: none; to your template, and you can put any css classes you want on it.

**Comment by twigkit** [comment]
Sorry didn't mean to close this - there remains the outstanding issue whether we would rather want to specify the display: none; in CSS and add the block after rendering. Plus like you said, be able to specify a class to add after rendering. What do you think?

**Comment by arsduo** [comment]
I'm thinking specifically of this sentence, which I think is what you mentioned in your second comment:

> If there is no inline rule (if, for instance, you defined display: none in an external stylesheet), Tempo will add style="display: block;" once the rendering has taken place.

So if you set display: none in an external stylesheet (perhaps with a common .unrenderedTemplate class), you wouldn't have fine control over the display property after the template is rendered.

A separate post-rendered class would also be great for cases where the template is partially visible beforehand -- for instance to hide "loading" elements and show the newly rendered content.

Since Tempo is so simple, I don't even think you'd need (or want) support to specify a class name -- it could just be hardcoded to tempo-rendered or something along that line.  

If I have a chance, I can try adding that -- I'd like to poke around more in the source code.  Otherwise, of course, I'd be happy to use it if you implemented it :)

Best,

Alex

**Comment by twigkit** [comment]
Hi Alex. We've just pushed an update which provides support for renderer event listeners (http://twigkit.github.com/tempo/#advanced). The Twitter example demonstrates this now (http://twigkit.github.com/tempo/examples/twitter). Let me know if this is an acceptable solution. Thanks again, Stefan

**Comment by mrolafsson** [comment]
Closed.
