### ISSUE TITLE
Using tempo with tabs 

### ISSUE THREAD

**Issue by utroda** [twigkit/tempo#80]
Hello,

I'm trying to break my template into tabs based on conditional templates.

```
            <div class="tab-pane active" id="businesses">

                <ul class="tiles">
                    <li data-template data-if-type="business">[[ name ]]</li>
                </ul>

            </div>

            <div class="tab-pane" id="events">
                <ul class="tiles">
                    <li data-template data-if-type="event">[[ name ]]</li>
                </ul>
            </div>

            <div class="tab-pane" id="attractions">
                <ul class="tiles">
                    <li data-template data-if-type="attraction">[[ name ]]</li>
                </ul>
            </div>

            <div class="tab-pane" id="default">
                <ul class="tiles">
                    <li data-template>[[ name ]]</li>
                </ul>
            </div>
```

Nothing will show up in the conditionals, only in the final data-template even though the conditions are met. Any idea on how to fix this?

**Comment by mrolafsson** [comment]
I'm not quite sure what this should look like...can you set up a jsfiddle that demonstrates this? I'm happy to help you debug then.

**Comment by utroda** [comment]
Heres a jsfiddle - http://jsfiddle.net/FxV6a/

We are using the boostrap tabs, and within each tab we want to should a ul of just "type" if its events, attractions, business. Whats happening is only the first condition will be met, and the items that meet the condition will be rendered where the default template is, not where the conditional template is.

**Comment by utroda** [comment]
I was wondering if any progress has been made with this issue? Heres an updated fiddle of the issue, - http://jsfiddle.net/FxV6a/1/

**Comment by mrolafsson** [comment]
Isn't it just that the `data-template` is in actuality the section? http://jsfiddle.net/4St9b/

**Comment by utroda** [comment]
Thanks for that, I guess we where looking at it the wrong way. Using data-template-for instead of data-if.
