### ISSUE TITLE
Nested if blocks should be interpreted

### ISSUE THREAD

**Issue by 2is10** [twigkit/tempo#82]
Using `{% if %} ... {% endif %}` inside another `{% if %}` block does not work properly.

http://jsfiddle.net/Px6LH/1/

**Comment by mrolafsson** [comment]
Hi, sorry for the late (bordering on non-) reply. I am aware that this doesn't work but I had some work under way on the 3.0 branch which would have allowed me to do this. Are you still using Tempo? Are you interested in the continued development of it?

**Comment by 2is10** [comment]
Thanks for the reply. No, we’ve migrated our projects – now using handlebars in one project and angular in another. I think [the HTML 5 `<template>` element](http://www.html5rocks.com/en/tutorials/webcomponents/template/) is probably the way of the future for simple client-side templates. Cheers.

**Comment by mrolafsson** [comment]
Alright -- again sorry that I wasn't responsive on this. Best of luck and thank you for your support in the past.
