### ISSUE TITLE
HTML data-template and empty data set

### ISSUE THREAD

**Issue by quantegy** [twigkit/tempo#90]
I scoured through the docs, and the issues, but I couldn't find an example of how to handle empty data results. I basically need to show a default template for empty data set, and I couldn't find a directive for this. Is there a data attribute like 'data-template-empty' that would allow me to display an empty content alternative?

**Comment by mrolafsson** [comment]
Hi, sorry for the late reply. Yes, you're right, that's not possible at present but an easy addition. Are you still using Tempo? Would you be interested in it's continued development?

**Comment by quantegy** [comment]
Sorry, unfortunately, due to a pressing deadline, I couldn't use tempo. It is a useful library, but the lack of an empty data set template option prevented me from using it.

**Comment by mrolafsson** [comment]
Hi! No problem -- I'm sorry I couldn't support you better at the time. Best of luck with your project!
