### ISSUE TITLE
Nested object in array

### ISSUE THREAD

**Issue by AllyReid** [twigkit/tempo#93]
How can I access the values of an object within my data array JSON?

e.g. 

``` json
sports:{
"0":"football",
"1":"golf",
"2":"basketball"
}
```

I have been using your nested examples but not having any luck getting it to work

**Comment by mrolafsson** [comment]
Can you give me an example of what you are trying to output this as? This is not an array so you would want to use `data-from-map` attribute: https://github.com/twigkit/tempo/blob/master/examples/data-from-map.html

**Comment by AllyReid** [comment]
Hi,

It's to display some profile information, e.g.

JSON:

``` json
postcode: "ABC 123"
region: "UK"
section: "Members"
sports:{
"0":"football",
"1":"golf",
"2":"basketball"
}
```

HTML:

``` html
<div class="inner" data-template>
  <div class="thumbnail-name">
    <img src="http://dummyimage.com/300/300/fff" alt="" data-src="{{image}}" />
    <h3>{{section}} {{region}}</h3>
  </div>
    <ul>
    <span>Sports</span>  
    <li>{{sports}}</li>
    </ul>
</div>
```

**Comment by mrolafsson** [comment]
If you supply a Fiddle I could help you with this but this is a straight forward case of what I said. You need to handle the iteration of `sports` not just refer to a single object. And since Sports is not an array you need to traverse it as a map.

**Comment by mrolafsson** [comment]
There were a few issues with your example including invalid JSON, lack of iteration etc. Here you'll find a working example: http://jsfiddle.net/mr_olafsson/67yreg0h/

Check out nested templates: http://tempojs.com/#nested-templates

```
<ol id="list">
    <li data-template data-from-map>{{value}} - {{key | append '@marx.com'}}</li>
</ol>
```

**Comment by AllyReid** [comment]
Wow fixed the json and it works perfectly! 

Thanks for your quick replies and examples.

Thanks for such a great tool.

**Comment by mrolafsson** [comment]
You're welcome! ;)
